name = "sahel-financial-system"
main = ".next/server/app/page.tsx"
compatibility_date = "2024-01-01"

[env.production]
name = "sahel-financial-system"

[env.staging]
name = "sahel-financial-system-staging"

[[d1_databases]]
binding = "DB"
database_name = "financial-db"
database_id = "your-database-id"

[vars]
JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production"

[build]
command = "npm run build"

[env.production.vars]
NODE_ENV = "production"

[env.staging.vars]
NODE_ENV = "staging"